version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapipass
      POSTGRES_DB: fastapidb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
