version: '3.8'

services:
  web1:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db

  web2:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgis/postgis:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    depends_on:
      - web1
      - web2

volumes:
  postgres_data:
